couchbaselabs/cbforest

CBForest.xcodeproj/project.pbxproj
When one of embedded subprojects have this property value, set to NO, parent project will generate generic xcode archive instead of IPA
Fix according to these answer
http://stackoverflow.com/questions/10715211/cannot-generate-ios-app-archive-in-xcode
=> Changed project "SKIP_INSTALL" property to YES, to allow generate IPA package instead of Generic Xcode Archives

Java/jni/native_database.cc, Java/jni/native_document.cc, Java/src/com/couchbase/cbforest/Constants.java, Java/src/com/couchbase/cbforest/Database.java, Java/src/com/couchbase/cbforest/Document.java, Java/src/com/couchbase/cbforest/DocumentIterator.java
New binding methods:
- Database.rekey()
- Database.compact()
- Database.getDocumentBySequence(long)
- Document.hasRevisionBody()
- Document.purgeRevision()
Others:
- Added helper methods to JNI Java code
=> Update JNI bindings to catchup recent C-API updates and Added helper methods

CBForest/VersionedDocument.cc, Java/jni/native_document.cc
@snej Thank you for your fix for insertRevisionWithHistory() method and test for it. This PR is fixes for other issues related with insertRevisionWithHistory().
Changes:
- VersionedDocument: update _flags instance variable when updateMeta() method is called.
- native_document.cc: call updateSelectin() method to update currently selected revision information in insertRevisionWithHistory(). otherwise, need to call selectCurrentRev() method.
- native_document.cc:  jobjectArray jhistory is String[]. So fixed binding codes.
=> Fixed insertRevisionWithHistory method related issues.

C/c4Database.cc, CBForest/Collatable.cc, Java/jni/native_database.cc, Java/jni/native_document.cc, Java/jni/native_documentiterator.cc, Java/jni/native_queryIterator.cc, Java/jni/native_view.cc, Java/src/com/couchbase/cbforest/Constants.java, Java/src/com/couchbase/cbforest/Database.java, Java/src/com/couchbase/cbforest/Document.java, Java/src/com/couchbase/cbforest/DocumentIterator.java, Java/src/com/couchbase/cbforest/QueryIterator.java, Java/src/com/couchbase/cbforest/View.java
CBForest:
- c4Database.cc: Update C4Document.sequence value after save the document
- Collatable.cc: set precision level to isotherm for double value
JNI:
- Added sequence into Document which is transferred value between Java and Native
- Make initEnumerateAllDocs to support all option values
- Make query iterator can return document sequence value
- Fixed the C4Key array passing issue for query
- Update initWithDocHandle(...) in native_document.cc : Added to call c4doc_selectCurrentRevision(doc) to select current revision, and removed redundant Java instance variable update methods, which are covered by udpateSelection() and updateRevIDAndFlags().
- Consolidated Database.iterateChanges(...) and DocumentIterator.initEnumerateChanges(...)
- Constants.java: Added CBForestError constants
=> Fixed CBForest and JNI to address View related issues.

C/c4View.cc, CBForest/GeoIndex.cc, Java/jni/native_glue.cc, Java/jni/native_glue.hh, Java/jni/native_view.cc
- compile error with `std::max`: it requires exact same type.
- `valueBufs.push_back(jbyteArraySlice(env, jvalue));` caused malloc/free error on OS X
- calling GetStringUTFChars with null jstring parameter causes runtime crash on OS X
=> Fixed JNI compilation error and runtime errors with Java (JDK) on OS X

C/c4Document.cc, Java/jni/native_document.cc
* c4doc_selectCurrentRevision doesn't need to load the doc body.
* Warn if trying to select other revisions when the doc body isn't loaded.
* Fixed some error handling in the insert-revision methods
* JNI method Document.initWithDocHandle doesn't need to select the
current revision; it's already selected by default.
This should improve performance of all-docs enumeration in Java, because
it no longer ends up loading the bodies of all the documents.
=> C API: Fixes for C4Documents loaded without their bodies

C/c4.exp, C/c4.h, C/c4Database.cc, Java/jni/native_document.cc
If the current revision is selected, the Java String in Document.revID can be stored into .selectedRevID instead of creating another String. This will save creating an object every time a Document is initialized, and may speed up the allDocuments iteration.
Hideki, could you please try this, and merge it if it works?
=> JNI optimization for Document (speed up updateSelection fn)

C/c4Document.cc, C/c4Impl.hh, C/c4View.cc, C/c4View.h, CBForest.xcodeproj/project.pbxproj, CBForest/MapReduceIndex.cc, CBForest/MapReduceIndex.hh, CBForest/VersionedDocument.hh, Java/jni/native_glue.hh, Java/jni/native_indexer.cc, Java/jni/native_view.cc, Java/src/com/couchbase/cbforest/Indexer.java, Java/src/com/couchbase/cbforest/View.java
Broke the indexing API out into a new class, Indexer.
An Indexer is created with an array of views to be indexed.
Before calling a view's map function, call Indexer.shouldIndex to check
whether that view needs that sequence to be indexed; if not, skip it.
When emitting key/value pairs, you'll need to specify which view
they're for.
=> Java: Support for simultaneous indexing of multiple views

Java/jni/native_indexer.cc
Fixed calling c4indexer_emit not using viewNumber.
=> Java: Fix Indexer_emit not using viewNumber

CBForest/Collatable.cc, CBForest/slice.cc
- VC requires `#include <algorithm>` explicitly to use `std::max`
- VC does not support X?:Y
=> Fixed #53 - Fixed compilation error on Windows with VC++

CBForest.xcodeproj/project.pbxproj
Disable GENERATE_MASTER_OBJECT_FILE in 'CBForest static' target to fix 'unable to open object file' warning messages.
For couchbase/couchbase-lite-ios#1054
=> Disable GENERATE_MASTER_OBJECT_FILE setting in 'CBForest static' target

CBForest/DocEnumerator.cc, CBForest/Index.cc
ForestDB's iterator can stop prematurely when iterating in descending
order while skipping deleted docs. The workaround here avoids setting
the FDB_ITR_NO_DELETES flag. Have filed a ForestDB issue to get a real
fix.
Fixes #1082
=> Work around ForestDB bug in descending view queries

CBForest/DocEnumerator.cc
Based on the backtrace in couchbase/couchbase-lite-java-core#971, it
appears that the fdb_iterator_get_metaonly() call added as part of the
descending-view-query workaround may return FDB_STATUS_ITERATOR_FAIL.
I think this can happen if there are no rows returned in the iteration
at all -- it's the same reason the pre-existing call to
fdb_iterator_get_metaonly in the getDoc() method below checks for that
error.
So I've changed the workaround code to ignore error returns.
Fixes couchbase/couchbase-lite-java-core#971 ... I think
=> Fix possible exception in previous fix (for descending view queries)

CBForest.xcodeproj/project.pbxproj, Java/jni/native_document.cc, Java/jni/native_glue.cc, Java/jni/native_glue.hh
This function can use an arbitrary number of local JNI refs (one for
each item in the history array), so preallocate a new local frame with
enough room for them.
(Also clarified a comment about critical allocation just below, to make
it more clear that JNI allocations are illegal until the critical ref
is released.)
Fixes couchbase/couchbase-lite-android#782 (I think; needs testing)
=> JNI: Fixed local-refs overflow in Document.insertRevisionWithHistory

C/c4Base.h, C/c4View.cc, CBForest/Index.cc, CBForest/Index.hh
It will return new error kC4ErrorIndexBusy.
=> Prevent closing a C4View while its index is enumerating or updating

CBForest/Database.cc
Crash occurs in workaround, Removed the workaround codes as https://issues.couchbase.com/browse/MB-18753 is already merged into stable branch of forestdb repo (by @hisundar).
=> Fixed #81 - Crash in ForestDB (filemgr_is_fully_resident)

.gitmodules
Since many corporate firewalls block the git:// protocol port, HTTPS seems to be a better choice for git submodules.
=> Use HTTPS protocol for all git submodules

C/c4Document.cc, CBForest/LogInternal.hh
Forest FC when save record (Note: ForestDB error code = -39)
https://github.com/couchbase/couchbase-lite-android/issues/909
- Fixed scenario: Thread1: push replicator, Thread2: keep inserting.
- This PR along with native logging code for Android.
=> Fixed another scenario of FDB_RESULT_HANDLE_BUSY error.

README.md
This will allow cbforest visitors to go the public links for forestdb and couchstore repositories.
=> Correct URL links for forestdb & couchstore in README

C/c4Database.cc, C/c4Document.cc, C/c4ExpiryEnumerator.cc
I found some missing database locking in the document-expiration code.
=> C API: Concurrency fixes for doc-expiration functions

xcconfigs/CBForest static.xcconfig
Set GENERATE_MASTER_OBJECT_FILE=NO to fix unable to open object file warning messages when the library is used.
Reference: https://github.com/couchbase/couchbase-lite-ios/issues/1376.
=> Set GENERATE_MASTER_OBJECT_FILE=NO

CBForest/Database.cc, CBForest/LogInternal.hh
- Issue: LogLevel is not checked.
- Solution: just using `__android_log_write()` which is logging method for android native library, instead of `fprintf()`.
=> Fixed #100 - Android: LogLevel does not effect for Android.

xcconfigs/Project.xcconfig
Set tvOS deployment target to 9.0.
Reference: https://github.com/couchbase/couchbase-lite-ios/issues/1387
=> Fix tvOS build warnings

Java/src/com/couchbase/cbforest/DocumentIterator.java
Ticket: https://github.com/couchbase/couchbase-lite-java-core/issues/1441
Description: In case forestdb store is already closed when closing forestdb iterator, fdb_iterator_close() causes crash. This scenario could be happen because DocumentIterator.free(handle) is called from finalize(). To avoid this scenario, DocumentIterator should provide `public void close()` method to allow Java codes close DocumentIterator explicitly.
=> Fixed: ForestDB: Query.setLimit() could cause crashes.

C/c4Database.cc, C/c4DocEnumerator.cc, C/c4Document.cc, C/c4ExpiryEnumerator.cc, C/c4Impl.hh, C/c4View.cc, CBForest Tests/Database_Test.mm, CBForest Tests/GeoIndex_Test.mm, CBForest Tests/Index_Test.mm, CBForest Tests/MapReduce_Test.mm, CBForest Tests/VersionedDocument_Tests.mm, CBForest/Database.cc, CBForest/Database.hh, CBForest/LogInternal.hh, CBForest/MapReduceIndex.cc, CBForest/MapReduceIndex.hh
A bug in the RefCounted class's design was causing an assertion failure in its destructor, causing the process to abort because in C++11 it's a fatal error for a destructor to throw an exception. Fixed this and refactored two other classes so their destructors weren't doing work that could throw.
Fixes #105.
=> Fixed crash in c4view_open, and other potential destructor-triggered crashes

C/c4DocEnumerator.cc
Original ticket: https://github.com/couchbase/couchbase-lite-java-core/issues/1597
Functional Test creates concurrent scenario with pull replicator inserts docs and listener handles /_all_docs REST API request. As cbforest iterator’s next() method accesses forestdb file without having mutex, beginTransaction() or endTransaction() which are called from pull replicator fails with DB Handle Busy error (-39).
=> Fixed Java Core Issue 1597 - P2P - ForestDB Error: forceInsert()

CBForest/Collatable.mm
* WIth xcode 8.3, the error is non-portable path to file '"Error.hh"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path].
* Imported Error.hh instead of error.hh.
=> Fixed xcode 8.3 build error
